create database vmainen_afrikantahti;
select vmainen_afrikantahti;
create table cards (Cardnum int, Name varchar(255), Effect varchar(255));
INSERT INTO cards VALUES ('1', 'Cock and ball torture', 'You fucking instadie');
INSERT INTO cards VALUES ('2', 'Jesus', 'Voit kulkea normaalilla silmäluvulla vedessä vaikka sinulla ei olisi rahaa laivaan. [vain vesialueella]'); 
INSERT INTO cards VALUES ('3', '9/11 part 2 electric boogaloo', 'Saat ilmaisen lennon. [vain lentokentällä]');
INSERT INTO cards VALUES ('4', 'Ketamine', 'Your next die throw to move is doubled');
INSERT INTO cards VALUES ('5', 'Niilo22 psykoosi', 'You cannot move during your next turn');
INSERT INTO cards VALUES ('6', 'Redargeri', 'The player on your left can decide every other turn where you go for the rest of the game');
INSERT INTO cards VALUES ('7', 'Maxikola', 'Roastaa viereistäsi pelaajaa minuutin verran');
INSERT INTO cards VALUES ('8', 'Digitimepay', 'Kaikki pelaajat laulavat karaokena “Trump22 - Digitimepay” by Proheppe');
INSERT INTO cards VALUES ('9', 'Karvanaama', 'Kaikki pelaajat haukkuvat pelaavia karvanaamoja kaksi minuuttia');
INSERT INTO cards VALUES ('10', 'STFU', 'Alexa play “STFU” by Pink Guy.');
INSERT INTO cards VALUES ('11', 'Autism', 'Jokainen pelaaja huutaa mahdollisimman autistisesti');
INSERT INTO cards VALUES ('12', 'Dyslexia', 'Et saa lukea kortteja loppupelin verran, muut lukevat sinulle. Muut voivat valehdella halutessaan.');
INSERT INTO cards VALUES ('13', 'Joelin tanssimoovit', 'Pelin loppuun asti, jos joku pelaajista kertoo sinulle, että sinun pitää tanssia, tanssi.');
INSERT INTO cards VALUES ('14', 'Commit selfdie', 'Pyydä toista pelaajaa kertomaan sinusta nolo tarina.');
INSERT INTO cards VALUES ('15', 'Quick fire questions', 'Jokainen pelaaja kysyy kortin nostajalta kysymyksen. Kysymys voi olla mitä tahansa.');
INSERT INTO cards VALUES ('16', 'Talviklassikko', 'Mikäli ulkona sataa lunta ja lähellä on lumikinos, haasta joku pelaajista talviklassikkoon, häviäjä poistetaan pelistä');
INSERT INTO cards VALUES ('17', 'Pyhiinvaellus', 'Joku pelaajista joutuu kävelemään paikalle, josta voi nähdä Kivikon mäkin. Kuka tahansa pelaajista saa pelata pyhiinvaeltajan puolesta.');
INSERT INTO cards VALUES ('18', 'Distrobat', 'Pystyt puukottamaan muita pelaajia kirveellä päähän laudalla jos pääset samaan ruutuun. Pelaaja kuolee ja saat tämän rahat ja Inkan Aarteen/Afrikan Tähden/hevosenkengän mikäli hänellä on se. Kestää loppupelin ');
INSERT INTO cards VALUES ('19', 'Holokausti', 'Kaikki vähemmistön edustajat pelissä kuolevat');
INSERT INTO cards VALUES ('20', 'I’m problem ist my computer', '“Lag” for the rest of the game. This means that each turn you must throw a die. If it lands on 1-3, you can proceed with the turn. Otherwise, that turn is skipped. ');
INSERT INTO cards VALUES ('21', 'Epic animu battle', 'Kaksi pelaajaa vetää taistelun jossakin pelissä. ');
INSERT INTO cards VALUES ('22', 'Weeb ', 'Speak broken Japanese for the rest of the game.');
INSERT INTO cards VALUES ('23', 'Mario', 'Speak broken Italian for the rest of the game.');
INSERT INTO cards VALUES ('24', 'Schaalfen Und Laafen', 'Speak in broken German for the rest of the game.');
INSERT INTO cards VALUES ('25', 'Rickroll', 'Rick roll plays on loop for the rest of the game.');
INSERT INTO cards VALUES ('26', 'Koulukiussaaja', 'Valitse yksi pelaaja. Vittuile pelaajalle koko loppupelin.');
INSERT INTO cards VALUES ('27', 'You’ve been Gnomed!', 'Nothing happens. Fuck you.');
INSERT INTO cards VALUES ('28', 'Dibs Rips', 'Kun joku pelaaja kuolee saat laittaa “dibsit” hänen tavaroihin ja ottaa ne. ');
INSERT INTO cards VALUES ('29', 'Vaalit', 'Äänestäkää siitä kuka kuolee. Eniten ääniä saanut kuolee.');
INSERT INTO cards VALUES ('30', 'Reach häx', 'Voit avata minkä tahansa kiekon laudalta normaalihintaan, riippumatta sijainnistasi');
INSERT INTO cards VALUES ('31', 'No U', 'Käännä seuraava sinuun kohdistuva kortti sen nostajaa päin.');
INSERT INTO cards VALUES ('32', 'Reeeeee', 'Huuda Reeeeee niin kovaa kun pystyt.');
INSERT INTO cards VALUES ('33', 'Jag Tycker Om många saker och Tunnelbanan', 'Puhu paskalla Homoruotsalaisaksentilla loppupelin ajan. ');
INSERT INTO cards VALUES ('34', 'Tuu Mukaan peliin mukaan', 'Kaikki laulaa karaokena Yu-gi-oh GX:n suomidubin intron.');
INSERT INTO cards VALUES ('35', 'Vaikea valinta', 'Loppupelin ajan kun sinun pitää nostaa kortti, saat nostaa kaksi korttia ja valita niistä toisen.');
INSERT INTO cards VALUES ('36', 'Call the ambulance, but not for me', 'Seuraavan kerran kun kohtaat rosvon, ammut sitä päähän voon ja et menetä mitään.');
INSERT INTO cards VALUES ('37', 'Tuplapotti', 'Loppupelin ajan voit myydä jalokiviä tuplahinnalla.');
INSERT INTO cards VALUES ('38', 'Sivistymätön mölli', 'Jokainen kertoo lempiasiansa Niilo22:esta. Jos vastaaja ei tiedä kuka Niilo on, hän kuolee');
INSERT INTO cards VALUES ('39', 'Pokeri', 'Kaikki pelaajat pelaavat kolme kierroksen pokeria pelirahoillaan');
INSERT INTO cards VALUES ('40', 'Jokeri pokeri poks, kliketi klaketi kloks', 'Jokainen saa pokerikäden. Huonoimman käden omaava kuolee.');
INSERT INTO cards VALUES ('41', 'Me sad, me go kill self', 'Voit tehdä itsemurhan milloin tahansa menettämättä mitään');
INSERT INTO cards VALUES ('42', 'Huijaaminen on sallittua jos sitä ei huomata', 'Saat katsoa pelinappulasi viereiset kiekot vapaasti loppupelin ajan.');
INSERT INTO cards VALUES ('43', 'Hare Krishna ja tälleen', 'Puhu paskalla tech support aksentilla loppupelin');
INSERT INTO cards VALUES ('44', 'Go commit die', 'Tapa yksi pelaaja');
INSERT INTO cards VALUES ('45', 'Mä en nää mitään', ' Pelaa seuraavat 5 vuoroa sokkona. Muut pelaajat voivat sabotoida sinua');
INSERT INTO cards VALUES ('46', 'Rahat tiskiin ja jumankauta sassia', 'Kaikki pelaajat menettävät rahansa');
INSERT INTO cards VALUES ('47', 'Nuclear Holocaust', 'Kaikki pelaajat kuolevat');
INSERT INTO cards VALUES ('48', 'Tunnelbanan ', ' Fast Travel anywhere');
INSERT INTO cards VALUES ('49', 'Taksi roastaa', ' Aloittakaa roast battle. Kortin nostaja on tuomari. Häviäjä kuolee.');
INSERT INTO cards VALUES ('50', 'Coin tossaja', ' Heitä kolikkoa. Kruuna = Kuolet, Klaava = Saat 200.');
INSERT INTO cards VALUES ('51', 'Lahjus', 'Saat 500');
INSERT INTO cards VALUES ('52', 'Rahaa ja jumankauta sassia ', 'Vie muilta pelaajilta puolet heidän rahoistaan, mutta he kaikki saavat tappaa sinut, mikäli törmäävät sinuun');
INSERT INTO cards VALUES ('53', 'Kuuma peruna', 'Kortin nostaja saa “kuuman perunan”, jonka hänen pitää antaa toiselle pelaajalle kolmen vuoron aikana koskettamalla heitä. Mikäli et anna sitä kenellekkeen kolmen vuoron aikana, kuolet ja peruna siirtyy lähimmälle pelaajalle ');
INSERT INTO cards VALUES ('54', 'Varas', 'Vie keneltä tahansa pelaajalta kaikki hänen rahansa. Hän saa juosta perässäsi IRL ja ottaa rahansa takaisin. Mikäli hän ei jaksa enää jahdata sinua voit pitää rahat.');
INSERT INTO cards VALUES ('55', 'Tveet tvoot', 'Mikäli jollakin pelaajista on Twitter, postaa sinne jotakin tyhmää.');
INSERT INTO cards VALUES ('56', 'Seasick', 'Et voi matkustaa vedessä koko loppupelin');
INSERT INTO cards VALUES ('57', 'Desertsick', ' Et voi kulkea suoraan kuivan alueen läpi loppupelin, joudut kulkemaan rannikon kautta.');
INSERT INTO cards VALUES ('58', 'Orja', 'Anna kenelle tahansa pelaajalle seuraava kiekko jonka nostat. Et saa nostaa kiekkoa, ennen kuin kerrot kenelle annat sen');
INSERT INTO cards VALUES ('59', 'I’m going to say the N-word', ' Mene suoraan Madakaskariin (jos olet eri laudalla, menet silti sinne jumalauda). Mikäli sinulla on Seasick, se on voi voi.');
INSERT INTO cards VALUES ('60', 'Jäähy', 'Poistu pelistä 5 minuutiksi. Kuka tahansa voi liikutella sinun pelinappulaasi. ');
INSERT INTO cards VALUES ('61', 'Full house', 'Saat suoraan Afrikan Tähden (riippumatta laudasta, fuck you). ');
INSERT INTO cards VALUES ('62', 'Royale Flushi', 'Saat hevosenkengän/onnenauringon mikäli jollakin on Afrikan Tähti/Kultainen Aurinkopoika.');
INSERT INTO cards VALUES ('63', 'ummenen kierrosta kentan umpari Jumalauda', ' Juokse pelipaikan ympäri 10 kierrosta. Taas kerran pelinappulaasi voi liikuttaa sen aikana.');
INSERT INTO cards VALUES ('64', 'Table flip', 'Flippaa pelilauta. (Joudut siivoamaan sen)');
INSERT INTO cards VALUES ('65', 'Itkupotkuraivari', 'Vedä itkupotkuraivareita lattialla 5 minuuttia');
INSERT INTO cards VALUES ('66', 'Nupoleon', 'Mene St. Helenalle (jos olet eri laudalla, menet silti sinne jumalauda).');
INSERT INTO cards VALUES ('67', 'Paluulento', 'Mene suoraan takaisin kaupunkiin, josta aloitit.');
INSERT INTO cards VALUES ('68', 'Kaikki inekseen', 'Laita kaikki jo käännetyt kiekot takaisin peliin.');
INSERT INTO cards VALUES ('69', 'How ‘bout no', 'Voit kieltäytyä mistä tahansa haasteesta kerran');
INSERT INTO cards VALUES ('70', 'Panomiäs', 'Päättäkää kuka pöydässä on kovin panomies. Hän saa 600.');
INSERT INTO cards VALUES ('71', 'I’m in control now bitch', 'Saat ohjata kaikkia pelaajia heidän seuraavilla vuoroilla.');
INSERT INTO cards VALUES ('72', 'Noniin, aloitetaampas alusta', 'Peli alkaa alusta, koska fuck you all and your fucking effort.');
INSERT INTO cards VALUES ('73', 'Let’s go get some ramen, buddy!', 'Roni joutuu puhumaan Nendo-äänellä pelin loppuun asti.');
INSERT INTO cards VALUES ('74', 'Its gonna be huge, ok?', 'Imitoi Trumppia loppupeli');
INSERT INTO cards VALUES ('75', 'Olen paras pressa, Kekkonen on perseestä', 'Imitoi Sauli Niinistöä loppupeli');
INSERT INTO cards VALUES ('76', 'LIKE OMG! TOTES LEGIT!', 'Puhu basic bitch äänellä loppupeli');
INSERT INTO cards VALUES ('77', 'Michelle, I am Bohnen', ' Puhu kuin Obama loppupelin');
INSERT INTO cards VALUES ('78', 'Ketamine, I need ', 'Puhu kuin Yoda loppupelin, sinun täytyy.');
INSERT INTO cards VALUES ('79', 'Mykkäkoulu', 'Kukaan ei sano mitään viiteen minuuttiin. Mikäli puhut tämän aikana kuolet.');
INSERT INTO cards VALUES ('80', 'What it do you magnificent bastards, it’s papa Franku in the house', 'Puhu kuin Filthy Frank loppupeli.');
INSERT INTO cards VALUES ('81', 'Chikatto Chikatto chika chika', 'Kaikki pelaajat vetävät Chika dancen tai laulavat sen karaokessa, mikäli ei löydy tanssimooveja');
INSERT INTO cards VALUES ('82', 'Switch-uppi ', 'Vaihda lautaa, siirry aloituskaupunkiin');
INSERT INTO cards VALUES ('83', 'Autism rant', 'Vuoropelaaja puhuu jostain paskasta 5 minuuttia putkeen ilman että kukaan keskeyttää. Peli jatkuu tämän jälkeen.');
INSERT INTO cards VALUES ('84', 'Bussin’ it down sexual style no cap', 'Vuoropelaaja tekee parhaan tanssiliikkeensä. Muut päättävät, jos se oli GOATed with the sauce. Jos ei, pelaaja kuolee.');
INSERT INTO cards VALUES ('85', 'Edgemogging', ' Puhu kuin gen-alpha idiootti loppupelin.');
INSERT INTO cards VALUES ('86', 'All my apes, gone', 'aa puolet rahastasi muiden pelaajien kesken (peli-illan omat rahat.) *');
INSERT INTO cards VALUES ('87', 'YLYL', 'Seuraavan kerran kun naurat pelit aikana, kuolet');
INSERT INTO cards VALUES ('88', 'Deportation', 'Valitse yksi pelaaja. Hän vaihtaa lautaa ja päätyy valitsemaansa aloituskaupunkiin.');
INSERT INTO cards VALUES ('89', 'Teleports behind you', 'Siirry minkä tahansa pelaajan kohdalle.');
INSERT INTO cards VALUES ('90', 'Nothing ever happens 1', 'Mitään ei tapahdu, fuck you');
INSERT INTO cards VALUES ('91', 'Nothing ever happens 2', 'Mitään ei tapahdu, fuck you');
INSERT INTO cards VALUES ('92', 'Nothing ever happens 3', 'Mitään ei tapahdu, fuck you');
INSERT INTO cards VALUES ('93', 'Nothing ever happens 4', 'Mitään ei tapahdu, fuck you');
INSERT INTO cards VALUES ('94', 'Nothing ever happens 5', 'Mitään ei tapahdu, fuck you');
INSERT INTO cards VALUES ('95', 'Stonks ', 'Saat seuraavan arvotavarasta tulevat rahat markkoina 1mk:10 peliraha suhteella');
create user mrkill@localhost IDENTIFIED by 'nibs';
GRANT select on vmainen_afrikantahti. * to mrkill@localhost;